### ISSUE TITLE
You have requested a non-existent parameter "domain_constraint"

### ISSUE THREAD

**Issue by maximerochon** [infsy/Kentel#10]
Hi,

I pull the last version from GitHub but I get this error message :

[Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException]
 @You have requested a non-existent parameter "domain_constraint".

Did I need to to something specific to fix it ?

Thanks.
![2017-08-24_10-33-51](https://user-images.githubusercontent.com/19192915/29671622-057e642a-88b8-11e7-8512-c1b6c4bc99dd.jpg)

**Comment by infsy** [comment]
Hi Max,
This update is big for you because you're in an old version. 

This message is due to you parameters.yml.dist which contains a new parameter "domain_constraint" you have to fill. 
You could make a php composer.phar update and at the end it will ask you to precise the new parameters.

Otherwise, you could get back in your prev branche and try a new install of Kentel (in another dir) with your current database.
It could be a good idea to contact me on my cell phone, so i could help you with this upgrade.
Regards,
Cedric.

**Comment by infsy** [comment]
I close this one
